### ISSUE TITLE
feat: Add inspection time tracking

### ISSUE THREAD

**Issue by bryanlundberg** [bryanlundberg/NexusTimer#331]
It would be a good detail to save the inspection time for people who play using the inspection feature and display it alongside all other statistics.

![image](https://github.com/user-attachments/assets/d0bf5716-c37e-4548-969b-a6f211bc3757)

Note:
Right now, the application does not save any kind of inspection times; it needs to be adapted from the beginning.

**Comment by syrok94** [comment]
Hi @bryanlundberg , assign this to me and please let me know about inspection time.

**Comment by bryanlundberg** [comment]
> Hi @bryanlundberg , assign this to me and please let me know about inspection time.

Hi, inspection time its on settings:
![image](https://github.com/user-attachments/assets/6ebd6456-8eb1-4563-91eb-23eec792c7a6)

That feature gives a user 15 seconds of inspection time before starting the timer. [WCA](https://www.worldcubeassociation.org/regulations/#A3a1)

https://github.com/user-attachments/assets/76fbb5d1-0596-4626-9ec4-b42d5b87aecb

**Comment by bryanlundberg** [comment]
>  if a user is playing with inspection time or not but I need to what inspection time is?

Default inspection time 0

**Comment by syrok94** [comment]
Thanks 👍🏻.

**Comment by syrok94** [comment]
Hey @bryanlundberg ,
Is there an existing method to get the inspection time? Currently, the useTimer hook returns an inspectionTime, but it defaults to 1600. This might be due to re-renders causing it to reset.
I'm considering adding an inspectionTime field to the solve interface and saving the inspection time there. What are your thoughts on this approach?
